### ISSUE TITLE
panic: interface conversion: pdf.PdfObject is nil, not *pdf.PdfObjectInteger

### ISSUE THREAD

**Issue by Metalnem** [unidoc/unidoc#77]
Calling pdf.NewPdfReader on [this](https://github.com/unidoc/unidoc/files/1162406/panic-interface-conversion.pdf) malformed PDF file panics with the following message:

```
panic: interface conversion: pdf.PdfObject is nil, not *pdf.PdfObjectInteger
```

Stack trace:

```
goroutine 1 [running]:
github.com/unidoc/unidoc/pdf.(*PdfParser).decodeStream(0xc420018640, 0xc420015110, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/Metalnem/Go/src/github.com/unidoc/unidoc/pdf/pdfstream.go:58 +0x2b18
github.com/unidoc/unidoc/pdf.(*PdfParser).parseXrefStream(0xc420018640, 0x0, 0x12, 0xc420010f30, 0x1)
	/Users/Metalnem/Go/src/github.com/unidoc/unidoc/pdf/pdfparser.go:832 +0x4e3
github.com/unidoc/unidoc/pdf.(*PdfParser).parseXref(0xc420018640, 0x1000, 0x1000, 0xc4200be000)
	/Users/Metalnem/Go/src/github.com/unidoc/unidoc/pdf/pdfparser.go:991 +0x1fc
github.com/unidoc/unidoc/pdf.(*PdfParser).loadXrefs(0xc420018640, 0x0, 0xc420014de0, 0x0)
	/Users/Metalnem/Go/src/github.com/unidoc/unidoc/pdf/pdfparser.go:1093 +0x98d
github.com/unidoc/unidoc/pdf.NewParser(0x1233b80, 0xc42000e0e0, 0xc420014db0, 0x0, 0xc420014db0)
	/Users/Metalnem/Go/src/github.com/unidoc/unidoc/pdf/pdfparser.go:1298 +0xc8
github.com/unidoc/unidoc/pdf.NewPdfReader(0x1233b80, 0xc42000e0e0, 0xc42000e0e0, 0x0, 0x0)
	/Users/Metalnem/Go/src/github.com/unidoc/unidoc/pdf/reader.go:37 +0xa0
main.main()
	/Users/Metalnem/Go/src/github.com/metalnem/unifuzz/main.go:19 +0x102
exit status 2
```

This bug was found with the help of [go-fuzz](https://github.com/dvyukov/go-fuzz).

**Comment by Metalnem** [comment]
Fixed in v2.

**Comment by Metalnem** [comment]
Actually, this still exists in v2, it just takes a different input to trigger it. [Here](https://github.com/unidoc/unidoc/files/1162545/panic-interface-conversion.pdf) is another file that will cause the same panic in v2.
